[[mgr.prepend_keymap]]
on   = [ "c", "p" ]
run  = [ '''
    plugin copy-file-contents
''']
desc = "Copy the file content"

[[mgr.prepend_keymap]]
on   = "R"
run  = [ '''
    shell 'explorer.exe /select, "$(wslpath -w "$1")" || true'
''']
desc = "Reveal hovered file (WSL)"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"
