[mgr]
show_hidden = true

[opener]
open = [
    # { run = "xdg-open %s1",    desc = "Open", for = "linux" },
    { run = 'explorer.exe $(wslpath -w %s1) || true', desc = "Open (WSL)", for = "linux" },
    { run = "open %s",         desc = "Open", for = "macos" },
    { run = 'start "" %s1',    desc = "Open", for = "windows", orphan = true },
    { run = "termux-open %s1", desc = "Open", for = "android" },
]
edit = [
    { run = "${EDITOR:-vi} %s", desc = "$EDITOR",  for = "unix", block = true },
    { run = '%EDITOR% %s',      desc = "%EDITOR%", for = "windows", block = true },

    # { run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
    # { run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]
# reveal = [
#     { run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
#     { run = 'open -R "$1"',                         desc = "Reveal", for = "macos" },
#     { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
#     { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },

[preview]
max_width       = 1200
max_height      = 1800
